"""added one to many relationship

Revision ID: 93c14058c802
Revises: b9e80c82d7d4
Create Date: 2023-05-09 10:20:26.492716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c14058c802'
down_revision = 'b9e80c82d7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crystal', sa.Column('healer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crystal', 'healer', ['healer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crystal', type_='foreignkey')
    op.drop_column('crystal', 'healer_id')
    # ### end Alembic commands ###
